# Configuration file for the local environment
config.env.filename: "configs.local.yaml"

# Autodiscovery Id
autodiscovery.id: "0"

# Overwrite Console config
apikit.console.disabled: "false"

# Overwrite JSON Logger config
json:
  logger:
    priority:
      exception: "INFO"
      before-request: "INFO"
      after-request: "INFO"
      before-transform: "INFO"
      after-transform: "INFO"

# Overwrite HTTP Listener config
listener:
  host: "0.0.0.0"
  port: "8002"

# MySQL Config
mysqldb:
  host: "sql4.freemysqlhosting.net"
  port: "3306"
  username: "sql4441960"
  password: "![ar4QpFzGYLkCV9H9LthgSw==]"
  dbname: "sql4441960"